name: Exécution du script current_datetime

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v2

      - name: Rendre le script exécutable
        run: chmod +x current_datetime.sh

      - name: Exécuter le script
        run: ./current_datetime.sh
