name: Exécution du script check_file_exist.sh

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v2

      - name: Rendre le script exécutable
        run: chmod +x check_file_exist.sh

      - name: Exécuter le script
        run: ./check_file_exist.sh
